---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: restapp-rule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: rest-app.c-1a0d284.kyma-stage.shoot.live.k8s-hana.ondemand.com
    name: restapp
    port: 8080
