apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: restdemo
  name: restdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restdemo
    spec:
      containers:
      - image: docker.io/sundarvc/restdemo:v0.3
        name: restdemo
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restdemosvc
  name: restdemosvc
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restdemosvc
  type: ClusterIP
status:
  loadBalancer: {}
