apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: restapp
  name: restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restapp
    spec:
      containers:
      - image: docker.io/sundarvc/restdemo:v0.4
        name: restapp
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: restapp
  name: restapp
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: restapp
  type: ClusterIP
status:
  loadBalancer: {}
